services:
  postgres:
    image: postgres:latest
    container_name: store_backend
    ports:
      - '5432:5432'  # IPv4 mapping
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
